import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Nourishment from './Nourishment'
import ReservationForm from '../components/ReservationForm'
import SignIn from './SignIn'
import SignUp from './SignUp'
import TransactionHistory from './TransactionHistory'
import UserSettings from '../components/UserSettings'
import HotelDetails from '../components/HotelDetails'
import FoodDetails from '../components/FoodDetails'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>

      <footer>
      
      </footer>
    </div>
  )
}

export default Home
